### ISSUE TITLE
Local Energy feedback

### ISSUE THREAD

**Issue by PM-OCEA** [ischerr/SESH#24]
Community & locally owned:

- [x] Tab titles and chart titles not updated
- [x] Change the tab titles to 'time series', 'pipeline', 'by technology', 'by output', 'by ownership category'
- ~Main chart and data should be the progress towards the 1 GW target.  See what it looks like with the 2GW target for 2030 as well.~
- [x] Time series tab - full time series isn't showing
- ~Can you add the 2030 target to the pipeline chart as well?~

CHP:

- [x] Rename tab to 'Combined heat and power'

Heat networks:

- [x] What's the error message in the commentary section?
- [x] Add in other data tables in this section

**Comment by ischerr** [comment]
>     * Change the tab titles to 'time series', 'pipeline', 'by technology', 'by output', 'by ownership category'

Requires ESD update
